# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# TODO add something like https://gist.github.com/jgosmann/003e52db6959365c0ffda264776e7e44 to catch fixups
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
