#! /bin/bash

version=$(sed -n 's/const Version = "\([0-9]\+\.[0-9]\+\.[0-9]\+\)"/v\1/p' version.go)

if [[ -z $(grep "## \[$version\] - " CHANGELOG) ]]; then
    echo "Missing entry in CHANGELOG for $version" >&2
    exit 1
fi

if [[ -n $(grep "## \[$version\] - AUTOGENERATED" CHANGELOG) ]]; then
    echo "Please update CHANGELOG for $version" >&2
    exit 1
fi
