name: Coverage

on:
  push:
    branches:
      main
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: stable
      - name: Install dependencies
        run: go mod download
      - name: Test
        run: go test -v -coverprofile=coverage.out -coverpkg=$(go list ./... | paste -sd ",") ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f #v7.0.0
        with:
          use_oidc: true
          files: coverage.out
