name: Coverage

on:
  push:
    branches:
      main
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Install dependencies
        run: go mod download
      - name: Test
        run: go test -v -coverprofile=coverage.out -coverpkg=$(go list ./... | paste -sd ",") ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad #v5.5.3
        with:
          use_oidc: true
          files: coverage.out
